spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:usertest;MODE=MYSQL
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  sql:
    init:
      data-locations: classpath:/db/*
server:
  error:
    include-message: always
  port: 0
logging:
  level:
    org:
      springframework: info
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
