spring:
  datasource:
    url: jdbc:h2:mem:usertest;MODE=MYSQL
    username: sa
    password: password
#    driver-class-name: org.h2.Driver
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

  sql:
    init:
      data-locations: classpath:/db/*
