logging:
  level:
    org:
      springframework: info

server:
  error:
    include-message: always
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service
#  profiles:
#    active: test
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${spring.application.name}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:/db.migration,classpath:/db.datainit
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${spring.application.name}?createDatabaseIfNotExist=true
    user: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  cloud:
    config:
      enabled: false

#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 31536000000 # 1 year in Ms
##      expiration: 86400000 # 1 day in Ms
